Added an endpoint for getting list of accounts #7
VitonBaton/vehicle-information-system pull request #35
Opened 2022-07-19 15:23 UTC by mikan48

### What

Admin should be able to get information about all accounts in the system. There should be pagination with 20 accounts per page.

### How

Added new methods in accounts service for getting list of users. Added view models for page and accounts list. Added method in controller for account list with pagination.

### Affected Area

AccountsService.Constants.Logger
AccountsService.Controllers
AccountsService.Services
AccountsService.ViewModels

### PR Checklist

*Build*

 - [x] Build Succeeded

2022-07-19 15:49 UTC, the-17th-fox requested changes
Replace `if (users is null)` with `if (!users.Any())` 
If there are no users ToListAsync will return an empty list instead of null.

2022-07-19 15:57 UTC, the-17th-fox requested changes

2022-07-19 15:57 UTC, the-17th-fox commented on src/AccountsService/Services/AccountsSvc.cs
> +            }
Replace `if (users is null)` with `if (!users.Any())` 
If there are no users ToListAsync will return an empty list instead of null.

2022-07-20 17:15 UTC, VitonBaton approved these changes

2022-07-21 13:26 UTC, the-17th-fox approved these changes

2022-07-21 14:47 UTC, merged